version: "3.7"

services:
  notes-db:
    image: postgres:12.1
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/01-init-api-db.sh
    env_file:
      - ./.env


